In [81]:
import numpy as np
import pandas as pd
from sklearn.datasets import fetch_20newsgroups
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer, HashingVectorizer, CountVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.pipeline import Pipeline
from sklearn.cross_validation import cross_val_score, KFold

from nltk.stem import SnowballStemmer
from nltk.corpus import stopwords

from scipy.stats import sem

from nltk.tokenize import word_tokenize

import warnings
warnings.simplefilter("ignore")

import pandas as pd

In [17]:
news = fetch_20newsgroups(subset='all')

In [3]:
type(news.data)

list

In [4]:
news.target

array([10,  3, 17, ...,  3,  1,  7])

In [5]:
print(news.target_names)
print('\n')
type(news.target_names)

['alt.atheism', 'comp.graphics', 'comp.os.ms-windows.misc', 'comp.sys.ibm.pc.hardware', 'comp.sys.mac.hardware', 'comp.windows.x', 'misc.forsale', 'rec.autos', 'rec.motorcycles', 'rec.sport.baseball', 'rec.sport.hockey', 'sci.crypt', 'sci.electronics', 'sci.med', 'sci.space', 'soc.religion.christian', 'talk.politics.guns', 'talk.politics.mideast', 'talk.politics.misc', 'talk.religion.misc']




list

In [6]:
news.data[0]

"From: Mamatha Devineni Ratnam <mr47+@andrew.cmu.edu>\nSubject: Pens fans reactions\nOrganization: Post Office, Carnegie Mellon, Pittsburgh, PA\nLines: 12\nNNTP-Posting-Host: po4.andrew.cmu.edu\n\n\n\nI am sure some bashers of Pens fans are pretty confused about the lack\nof any kind of posts about the recent Pens massacre of the Devils. Actually,\nI am  bit puzzled too and a bit relieved. However, I am going to put an end\nto non-PIttsburghers' relief with a bit of praise for the Pens. Man, they\nare killing those Devils worse than I thought. Jagr just showed you why\nhe is much better than his regular season stats. He is also a lot\nfo fun to watch in the playoffs. Bowman should let JAgr have a lot of\nfun in the next couple of games since the Pens are going to beat the pulp out of Jersey anyway. I was very disappointed not to see the Islanders lose the final\nregular season game.          PENS RULE!!!\n\n"

In [7]:
news.target_names[0]

'alt.atheism'

In [18]:
Split_perc = 0.75
split_size = int(len(news.data)*Split_perc)

In [19]:
x_train = news.data[:split_size]
x_test = news.data[split_size:]
y_train = news.target[:split_size]
y_test = news.target[split_size:]

In [20]:
print('x_test : ',len(x_test))
print('x_train : ', len(x_train))
print('y_test : ',len(y_test))
print('y_train : ', len(y_train))

x_test :  4712
x_train :  14134
y_test :  4712
y_train :  14134


In [21]:
clf_1 = Pipeline([('vect', CountVectorizer()),
                 ('clf', MultinomialNB())])

In [22]:
clf_2 = Pipeline([('vect', HashingVectorizer(non_negative=True)),
                 ('clf', MultinomialNB())])

In [23]:
clf_3 = Pipeline([('vect', TfidfVectorizer()),
                 ('clf', MultinomialNB())])

In [24]:
def eval_cross_val(clfs, x,y,K):
    
    cv = KFold(len(y), K, shuffle=True, random_state=0)
    
    scores = cross_val_score(clf,x,y,cv=cv)
    print(scores)
    print(np.mean(scores))

In [25]:
clfs=[clf_1, clf_2, clf_3]
for clf in clfs:
    eval_cross_val(clf, news.data, news.target, 5)

[0.85782493 0.85725657 0.84664367 0.85911382 0.8458477 ]
0.853337340146793
[0.75543767 0.77659857 0.77049615 0.78508888 0.76200584]
0.7699254211904598
[0.84482759 0.85990979 0.84558238 0.85990979 0.84213319]
0.8504725482840962


In [50]:
stops = set(stopwords.words('english'))

In [51]:
clf_5 = Pipeline([
    ('vect', TfidfVectorizer(
        stop_words=stops,
    tokenize)), 
    ('clf', MultinomialNB())
                 ])

In [101]:
eval_cross_val(clf_5, f, news.target, 5)

ValueError: Found input variables with inconsistent numbers of samples: [35873849, 18846]

In [88]:
x = pd.DataFrame(news.data)

In [89]:
x.head()

0
0  From: Mamatha Devineni Ratnam <mr47+@andrew.cm...
1  From: mblawson@midway.ecn.uoknor.edu (Matthew ...
2  From: hilmi-er@dsv.su.se (Hilmi Eren)\nSubject...
3  From: guyd@austin.ibm.com (Guy Dawson)\nSubjec...
4  From: Alexander Samuel McDiarmid <am2o+@andrew...

In [96]:
def pre_process(text):
    
    #text = text.translate(str.maketrans('', '', string.punctuation))
    text = [word for word in text if word.lower() not in stopwords.words('english')]
    words = ""
    for i in text:
            stemmer = SnowballStemmer("english")
            words += (stemmer.stem(i))+" "
    return words

In [99]:
textFeatures = news['data'].copy()
textFeatures = textFeatures.apply(pre_process)
vectorizer = TfidfVectorizer("english")
features = vectorizer.fit_transform(textFeatures)

AttributeError: 'list' object has no attribute 'apply'

In [98]:
f = pre_process(news.data)